### ISSUE TITLE
toSNSTopic should return a Topic, not a CollectedTopic

### ISSUE THREAD

**Issue by Jinxit** [punchcard/punchcard#145]
The stream processing part is not really necessary, and it would make type inference much simpler.

**Comment by sam-goodwin** [comment]
Thanks for trying punchcard and discovering this problem. I was encoding the Stream that produced the Topic in its type, but that messes with inference. This PR should fix this https://github.com/punchcard/punchcard/pull/146

Until I release, the workaround is to just cast your CollectedTopic to `Topic<T>`
