### ISSUE TITLE
Lambda.ExecutorService seems to be ignoring memorySize and timeout props

### ISSUE THREAD

**Issue by pocesar** [punchcard/punchcard#64]
```ts
const executorService = new p.Lambda.ExecutorService({
  allowAllOutbound: true,
  memorySize: 512,
  timeout: cdk.Duration.seconds(15)
})
```

can't find any mention of those settings in the generated YAML, but I'll happily try to debug CDK / punchcard down to help track the issue if interested. The lambda function created still uses the default memory (128) and the default timeout (3 secs), so don't know where the issue happening. The issue in this case is that the task is timing out because of lack of memory (my stack is using around 171MB)

**Comment by sam-goodwin** [comment]
This was a bug introduced by the `Build` monad. Fix: https://github.com/punchcard/punchcard/pull/70
